name: macOS Build and Test
on: 
  push:
    paths:
      - 'PolyChatApp/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'PolyChatApp/**'
      - '.github/workflows/macos.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [6.2.2]
        qt_arch: [clang_64]
    env:
      targetName: PolyChatApp
    steps:
      # macos 11.0 默认环境变了,要指定
      - name: prepare env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools       
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build and test on macOS 
        run: |
          cd ./PolyChatApp
          qmake
          make
